apiVersion: v1
kind: Service
metadata:
  name: hivebox
  labels:
    app: hivebox
spec:
  selector:
    app: hivebox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP